// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Infrastructure.DataContext;

#nullable disable

namespace i_freeze.Migrations.Device
{
    [DbContext(typeof(DeviceContext))]
    partial class DeviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Infrastructure.Model.DeviceAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceAction");
                });

            modelBuilder.Entity("Infrastructure.Model.DeviceActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivateNetworkScan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivateProactiveScan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivateWhitelist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockPowerShell")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlockUntrustedIPs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableCamera")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableTethering")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisableUSB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnableUSBScan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsAdminDevice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsolateDevice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MuteMicrophone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystemVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TamperProtection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceActions");
                });
#pragma warning restore 612, 618
        }
    }
}
