// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Infrastructure.DataContext;

#nullable disable

namespace i_freeze.Migrations.ToggleButtonAction
{
    [DbContext(typeof(ToggleButtonActionContext))]
    partial class ToggleButtonActionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Infrastructure.Model.ToggleButtonAction", b =>
                {
                    b.Property<string>("Toggle_Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.HasKey("Toggle_Name");

                    b.ToTable("ToggleButtonAction");
                });
#pragma warning restore 612, 618
        }
    }
}
